### ISSUE TITLE
Signups

### ISSUE THREAD

**Issue by animilimina** [EjaraApp/data-sbx#3]
Nb of accounts successfully created.

**Comment by animilimina** [comment]
- [ ] Check which step of registration process creates a row in ejara.customer
- [ ] Check if event is collected in Amplitude
> - [ ] If yes, build view in Amplitude
> - [ ] Otherwise build query on ejara.customer table.


Query on customer table would look like:
```
SET @date_max = NOW();
SET @date_min = DATE_ADD(@date_max, INTERVAL -28 DAY);


SELECT COUNT(*)
FROM ejara.customer AS customer
	INNER JOIN ejara.customer_type AS customer_type ON customer.customer_type_id = customer_type.id
WHERE 0=0
	AND DATE_FORMAT(FROM_UNIXTIME(customer.date_creation / 1000), '%Y-%m-%d %H:%i:%s') BETWEEN @date_min AND @date_max
	AND customer.customer_type_id = 1
;
```

**Comment by Nemadede** [comment]
Putting the query in a .sql script
